# https://gethomepage.dev/en/configs/services

- Management:
    - Radarr:
        href: http://host_ip:7878/
        server: my-docker
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key:
    - Radarr 4K:
        href: http://host_ip:7879/
        server: my-docker
        container: radarr4k
        widget:
          type: radarr
          url: http://radarr4k:7878
          key:
    - Sonarr:
        href: http://host_ip:8989/
        server: my-docker
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key:
    - Bazarr:
        href: http://host_ip:6767/
        server: my-docker
        container: radarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key:

- Downloads:
    - Cloudflare:
        href: https://dash.cloudflare.com/
        server: my-docker
        container: cloudflared
        widget:
          type: cloudflared
          accountid:
          tunnelid:
          key:
    - Speedtest:
        href: https://host_ip:9443/
        server: my-docker
        container: speedtest-tracker
        widget:
          type: speedtest
          url: http://speedtest-tracker
    - Sabnzbd:
        href: http://host_ip:8080/
        server: my-docker
        container: sabnzbd
        widget:
          type: sabnzbd
          url: http://sabnzbd:8080
          key:
    - QbittorrentVPN:
        href: http://host_ip:8081/
        server: my-docker
        container: qbittorrentvpn
        widget:
          type: qbittorrent
          url: http://qbittorrentvpn:8081
          username:
          password:

- Media:
    - Plex:
        href: http://host_ip:32400/web/
        server: my-docker
        container: plex
        widget:
          type: plex
          fields: ["movies", "tv"]
          url: http://plex:32400
          key:
    - Tautulli:
        href: http://host_ip:8181/
        server: my-docker
        container: tautulli
        widget:
          type: tautulli
          url: http://tautulli:8181
          key:
    - Overseerr:
        href: http://host_ip:5055/
        server: my-docker
        container: overseerr
        widget:
          type: overseerr
          url: http://overseerr:5055
          key:
    - Prowlarr:
        href: http://host_ip:9696/
        server: my-docker
        container: prowlarr
        widget:
          type: prowlarr
          fields: ["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs"]
          url: http://prowlarr:9696
          key:

- Misc:
    - Home Assistant:
        href: http://host_ip:8123/
        server: my-docker
        container: homeassistant
        widget:
          type: homeassistant
          url: http://host_ip:8123
          key:
    - OPNSense:
        href: https://router_ip/
        ping: https://router_ip/
        widget:
          type: opnsense
          url: https://router_ip
          fields: ["wanUpload", "wanDownload"]
          username:
          password:
    - Adguard:
        href: http://router_ip:81/
        ping: http://router_ip:81/
        widget:
            type: adguard
            url: http://router_ip:81/
            username:
            password:
    - Unraid:
        href: http://host_ip/
        ping: http://host_ip/
    - Frigate:
        href: http://host_ip:5000/
        server: my-docker
        container: frigate

- Templates:
    - Car Status:
        href: http://host_ip:8123/
        server: my-docker
        container: homeassistant
        widget:
          type: homeassistant
          url: http://host_ip:8123
          key:
          custom:
            - template: "{{ states.device_tracker.car_location.state | capitalize }}"
              label: Location
            - template: "{{ states.lock.car_door_lock.state | capitalize }}"
              label: Doors
            - template: "{{ states.sensor.car_battery_level.state | int }}%"
              label: Battery
