---
- Bookmarks:
    - Unraid:
        - href: https://mercury.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          # icon: /icons/example.ico  # Path relative to Homepage's config directory
          abbr: UR

    - Code-server:
        - href: https://code-server.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          abbr: CD

    - Github:
        - href: https://github.com/
          abbr: GH

    - YouTube:
        - href: https://youtube.com/
          abbr: YT
