---
layout:
  Calendar:
    header: false
    style: column

  Management:
    header: false

  Downloads:
    header: false

  Media:
    header: false

  Network:
    header: false

  Bookmarks:
    style: row  # 'row' combined with 'columns' creates a horizontal bookmark bar
    columns: 4

fiveColumns: true

useEqualHeights: true

background: /images/dracula-solid.png

theme: dark

# color: gray  # Must be 'gray' for custom.css Dracula theme - it targets .theme-gray selector

cardBlur: xl

headerStyle: clean

# providers:
  # finnhub: {{HOMEPAGE_VAR_FINNHUB_TOKEN}}
  # openweathermap: {{HOMEPAGE_VAR_OPENWEATHERMAP_TOKEN}}

# favicon: icons/arrows.ico

# quicklaunch:
  # searchDescriptions: true
  # hideInternetSearch: true
  # showSearchSuggestions: true
  # hideVisitURL: true
  # provider: google
